### ISSUE TITLE
Make NavBar dynamic 

### ISSUE THREAD

**Issue by sngo103** [rummankarim/QuickEatz#7]
Add some JS to make the NavBar change according to whether the user is logged in. If the user is logged in, show `dashboard`, notifications icon, and profile icon with dropdown menu. If the user is not logged in, _don't_ show `dashboard` and instead of the two icons, show links to the `Login` page and `Create Account` page. Everything else should always be shown.

**Comment by TDLorenz** [comment]
Navbar now has state which displays dashboard if a user is logged in and directs to two different dashboard pages depending on the type of account(customer or vendor). Also this was implemented assuming that dashboard.js will be used for the Customer Dashboard page. The two icons also only display if the user is logged in.

**Comment by TDLorenz** [comment]
Navbar also now displays login and Sign Up which link to the login and create Account page if a user is not logged in
